### ISSUE TITLE
Criar uma nova branch

### ISSUE THREAD

**Issue by LetiSouza18** [LetiSouza18/desafio-github-markdown#1]
LetiMarinho, sugiro a criação de uma nova branch chamada 'contribuicao/LetiMarinho' para que nós nos organizemos melhor e possamos trabalhar sem interferir as alterações feitas pela outra pessoa. Eu também irei criar a minha ramificação para te ajudar.

**Comment by LetiMarinho** [comment]
Criada a branch contribuicao/LetiMarinho.

**Comment by LetiSouza18** [comment]
Criada a branch contribuicao/LetiMarinho.

**Comment by LetiSouza18** [comment]
Criada a branch contribuicao/LetiMarinho.
